version: "3.8"
services:
  api:
    restart: always
    hostname: api
    build: .
    ports:
      - "9090:9090"
    command: uvicorn app.main:api --host 0.0.0.0 --port 9090
    volumes:
      - ".:/app"
