version: '3.8'
services:
    api:
        restart: always
        hostname: api
        build: .
        ports:
            - '9090:8000'
        command: uvicorn app.main:api --host 0.0.0.0
        volumes:
            - ".:/app"
